services:
  neo4j:
    image: neo4j:latest
    volumes:
      - neo4j_data:/data
    environment:
      - NEO4J_AUTH=neo4j/testtest
    ports:
      - "7474:7474"
      - "7687:7687"
volumes:
  neo4j_data:
    driver: local
